apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: redash-proxy
  name: redash-proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redash-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redash-proxy
    spec:
      containers:
      - image: sovryn/redash-proxy
        imagePullPolicy: Always
        name: redash-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        envFrom:
        - secretRef:
            name: redash-proxy
        - secretRef:
            name: redash-proxy-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: redash-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:500674654096:certificate/4d342e91-c855-47ea-9c40-dea361b19d4f
spec:
  selector:
    app: redash-proxy
  ports:
    - port: 443
      targetPort: 3000
  type: LoadBalancer
